[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
encode_tic_tac_toe = "DR5UupfCnFyr28T3CKaVpZr4477Qmn1JhGnUD2jveSLQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matejdrazic-balov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
